### PR TITLE
Update gtts_token.py

### PR DESCRIPTION
**Pull request by guydipietro**
Add handling for when TKK is already rendered

### CODE REVIEW

**Comment by edif30** [comment]
I validated this change as well in my local environment.  TY!

**Comment by rgusso** [comment]
still failing, even after changing the code
```
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 57, in _get_token_key
    tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by edif30** [comment]
@rgusso I've been running this all day and not one single error.  While another instance running old version has errored several times.

**Comment by rgusso** [comment]
here:

```
    def _get_token_key(self):
        if self.token_key is not None:
            return self.token_key


        response = requests.get("https://translate.google.com/")
        line = response.text.split('\n')[-1]

        tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
        try:
            # Grab the token directly if already generated by function call
                result = re.search("\d{6}\.[0-9]+", tkk_expr).group(0)
        except AttributeError:
            # Generate the token using algorithm
            timestamp = calendar.timegm(time.gmtime())
            hours = int(math.floor(timestamp / 3600))
            a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
            b = re.search("b\\\\x3d(-?\d+);", tkk_expr).group(1)
            result = str(hours) + "." + str(int(a) + int(b))

        self.token_key = result
        return result
```

`python -m compileall /usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py /usr/local/lib/^Cthon2.7/dist-packages/gtts_token/gtts_token.pyc`


```
tts.save('/tmp/test.mp3')
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 59, in _get_token_key
    tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Am I missing something?

**Comment by Guy-Dipietro-Bose** [comment]
@rgusso that's the correct version. Is it failing everytime? The tests have passed on Travis (see the checks) and like edif30, I'm not seeing any failures. I've run the tests many times and I've not run into the issue you see above.

**Comment by rgusso** [comment]
@Guy-Dipietro-Bose everytime:

pip uninstall gTTS-token
pip install gTTS-token
updated the code...

```
root@metarsul:~# python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gtts import gTTS
>>> tts = gTTS('hello')
>>> tts.save('hello.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 59, in _get_token_key
    tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
>>> 

```

I uninstalled, reinstalled, 
and the error continues

**Comment by edif30** [comment]
So from the looks of that traceback the call is not making it into try: and erroring out prior.

One thing I noticed that sticks out is your indent on                 
```
result = re.search("\d{6}\.[0-9]+", tkk_expr).group(0)
```
is out of place.  I'm not a python expert but its the only thing I can see.

**Comment by guydipietro** [comment]
@rgusso It looks like you're running on Linux, perhaps that's an issue. You could try to do a curl (curl -A GET https://translate.google.com). See what you get back and plug that into an online regex tester and try the regex above. Also look for the string "TKK=" and see what that has.

**Comment by edif30** [comment]
@guydipietro I'm running on debian 9 myself.

**Comment by rgusso** [comment]
wow I just realized.
It appears that google blocked me! :\
i'll wait and try again..


```
root@metarsul:~# curl -A GET https://translate.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/sorry/index?continue=https://translate.google.com/&amp;q=EhAmADwBAAAAAPA8kf_-rI0aGO6UkN0FIhkA8aeDS38be0yss93ZpjegnFp2Fa4Tx7QGMgFy">here</A>.
</BODY></HTML>
```

maybe we can handle this too?

**Comment by Boudewijn26** [comment]
Thanks a lot for these fixes. I hope to be able to take a good look at them later today. I think working around any Google blockades falls outside the scope of this PR and would be best suited for another PR.

**Comment by rotcop4u2** [comment]
i have just updated the gtts-token.py and now i have this error.
```
Fri Sep 21 2018 03:55:44 GMT-0400 (Eastern Daylight Time)

Error executing service <ServiceCall tts.google_say (c:86e0b4f9926b40868312fae6ce2c747c): message=The current time is 3:55, Today's weather will be a cloudy, with a high of 77.04 degrees., entity_id=['media_player.basement_speaker'], cache=False>

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1117, in _event_to_service_call
    await service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tts/__init__.py", line 134, in async_say_handle
    options=options
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tts/__init__.py", line 300, in async_get_url
    engine, key, message, use_cache, language, options)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tts/__init__.py", line 313, in async_get_tts_audio
    message, language, options)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/tts/google.py", line 74, in async_get_tts_audio
    from gtts_token import gtts_token
  File "/srv/homeassistant/lib/python3.5/site-packages/gtts_token/gtts_token.py", line 84
    return a
           ^
SyntaxError: 'return' outside function
```

**Pull request merged**
