### PR TITLE
Analyze November 2020 API changes

### PR DESCRIPTION
**Pull request by Boudewijn26**

### CODE REVIEW

**Comment by pndurette** [comment]
Awesome writeup of the _current new_ situation, thanks for taking the time to do this and write it down!
I've only looked very briefly very myself (just at the requests using the Dev tools), but you're way ahead! 🙌 

I know Google is all into gRPC and Protobufs and all that, I wonder how much we'll be able to 'defuscate'.

**Comment by Boudewijn26** [comment]
Well, surprisingly this doesn't appear to be gRPC, but some other RPC framework. At the very least it's not protobuf. Data sent is just form encoded and what's received is JSONish, some extra characters to prevent abuse. So thankfully it's all still readable. I'm not familiar with the human readable format (if any) of gRPC, so I'm not the best judge there.

**Comment by ncpierson** [comment]
As a random JS developer who also had to deal with this change, I just wanted to say thanks for writing this doc @Boudewijn26 ! It made the debugging process *way* faster, and allowed me to rewrite the JS implementation ([google-translate-tts](https://github.com/ncpierson/google-translate-tts)) in one night. It looks like Google fully(?) made the switch to the new API within the last 24 hours or so.

Here is my

**Comment by Boudewijn26** [comment]
You are very much welcome @ncpierson. Your case was the exact reason for this elaborate of a document. Well, that and the duplication of python implementations between gTTS and Home Assistant. Glad I could be of help.

**Pull request merged**
